#!/usr/bin/python3
def raise_exception():
    print("{:d}".format(["Hello", 1, 2]))
